spring:
  application:
    name: projeto_extensao_fase3
  security:
    secret: "Access key"
    expirationTime: 15 # in minutes

  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_extensao_fase2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/projeto_extensao_fase2
    user: postgres
    password: root

# Admin user configuration
app:
  admin:
    email: ${ADMIN_EMAIL:admin@admin.com}
    password: ${ADMIN_PASSWORD:admin123}
    name: ${ADMIN_NAME:Admin}
    description: ${ADMIN_DESCRIPTION:Administrador do sistema}
    default-city: ${ADMIN_DEFAULT_CITY:Criciúma}
    default-specialty: ${ADMIN_DEFAULT_SPECIALTY:Engenharia de Software}
