INSERT INTO city (id, name, state) VALUES (4312, 'Abdon Batista', 'SC');
INSERT INTO city (id, name, state) VALUES (4313, 'Abelardo Luz', 'SC');
INSERT INTO city (id, name, state) VALUES (4314, 'Agrolândia', 'SC');
INSERT INTO city (id, name, state) VALUES (4315, 'Agronômica', 'SC');
INSERT INTO city (id, name, state) VALUES (4316, 'Água Doce', 'SC');
INSERT INTO city (id, name, state) VALUES (4317, 'Águas de Chapecó', 'SC');
INSERT INTO city (id, name, state) VALUES (4318, 'Águas Frias', 'SC');
INSERT INTO city (id, name, state) VALUES (4319, 'Águas Mornas', 'SC');
INSERT INTO city (id, name, state) VALUES (4320, 'Alfredo Wagner', 'SC');
INSERT INTO city (id, name, state) VALUES (4321, 'Alto Bela Vista', 'SC');
INSERT INTO city (id, name, state) VALUES (4322, 'Anchieta', 'SC');
INSERT INTO city (id, name, state) VALUES (4323, 'Angelina', 'SC');
INSERT INTO city (id, name, state) VALUES (4324, 'Anita Garibaldi', 'SC');
INSERT INTO city (id, name, state) VALUES (4325, 'Anitápolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4326, 'Antônio Carlos', 'SC');
INSERT INTO city (id, name, state) VALUES (4327, 'Apiúna', 'SC');
INSERT INTO city (id, name, state) VALUES (4328, 'Arabutã', 'SC');
INSERT INTO city (id, name, state) VALUES (4329, 'Araquari', 'SC');
INSERT INTO city (id, name, state) VALUES (4330, 'Araranguá', 'SC');
INSERT INTO city (id, name, state) VALUES (4331, 'Armazém', 'SC');
INSERT INTO city (id, name, state) VALUES (4332, 'Arroio Trinta', 'SC');
INSERT INTO city (id, name, state) VALUES (4333, 'Arvoredo', 'SC');
INSERT INTO city (id, name, state) VALUES (4334, 'Ascurra', 'SC');
INSERT INTO city (id, name, state) VALUES (4335, 'Atalanta', 'SC');
INSERT INTO city (id, name, state) VALUES (4336, 'Aurora', 'SC');
INSERT INTO city (id, name, state) VALUES (4337, 'Balneário Arroio do Silva', 'SC');
INSERT INTO city (id, name, state) VALUES (4338, 'Balneário Camboriú', 'SC');
INSERT INTO city (id, name, state) VALUES (4339, 'Balneário Barra do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4340, 'Balneário Gaivota', 'SC');
INSERT INTO city (id, name, state) VALUES (4341, 'Bandeirante', 'SC');
INSERT INTO city (id, name, state) VALUES (4342, 'Barra Bonita', 'SC');
INSERT INTO city (id, name, state) VALUES (4343, 'Barra Velha', 'SC');
INSERT INTO city (id, name, state) VALUES (4344, 'Bela Vista do Toldo', 'SC');
INSERT INTO city (id, name, state) VALUES (4345, 'Belmonte', 'SC');
INSERT INTO city (id, name, state) VALUES (4346, 'Benedito Novo', 'SC');
INSERT INTO city (id, name, state) VALUES (4347, 'Biguaçu', 'SC');
INSERT INTO city (id, name, state) VALUES (4348, 'Blumenau', 'SC');
INSERT INTO city (id, name, state) VALUES (4349, 'Bocaina do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4350, 'Bombinhas', 'SC');
INSERT INTO city (id, name, state) VALUES (4351, 'Bom Jardim da Serra', 'SC');
INSERT INTO city (id, name, state) VALUES (4352, 'Bom Jesus', 'SC');
INSERT INTO city (id, name, state) VALUES (4353, 'Bom Jesus do Oeste', 'SC');
INSERT INTO city (id, name, state) VALUES (4354, 'Bom Retiro', 'SC');
INSERT INTO city (id, name, state) VALUES (4355, 'Botuverá', 'SC');
INSERT INTO city (id, name, state) VALUES (4356, 'Braço do Norte', 'SC');
INSERT INTO city (id, name, state) VALUES (4357, 'Braço do Trombudo', 'SC');
INSERT INTO city (id, name, state) VALUES (4358, 'Brunópolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4359, 'Brusque', 'SC');
INSERT INTO city (id, name, state) VALUES (4360, 'Caçador', 'SC');
INSERT INTO city (id, name, state) VALUES (4361, 'Caibi', 'SC');
INSERT INTO city (id, name, state) VALUES (4362, 'Calmon', 'SC');
INSERT INTO city (id, name, state) VALUES (4363, 'Camboriú', 'SC');
INSERT INTO city (id, name, state) VALUES (4364, 'Capão Alto', 'SC');
INSERT INTO city (id, name, state) VALUES (4365, 'Campo Alegre', 'SC');
INSERT INTO city (id, name, state) VALUES (4366, 'Campo Belo do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4367, 'Campo Erê', 'SC');
INSERT INTO city (id, name, state) VALUES (4368, 'Campos Novos', 'SC');
INSERT INTO city (id, name, state) VALUES (4369, 'Canelinha', 'SC');
INSERT INTO city (id, name, state) VALUES (4370, 'Canoinhas', 'SC');
INSERT INTO city (id, name, state) VALUES (4371, 'Capinzal', 'SC');
INSERT INTO city (id, name, state) VALUES (4372, 'Capivari de Baixo', 'SC');
INSERT INTO city (id, name, state) VALUES (4373, 'Catanduvas', 'SC');
INSERT INTO city (id, name, state) VALUES (4374, 'Caxambu do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4375, 'Celso Ramos', 'SC');
INSERT INTO city (id, name, state) VALUES (4376, 'Cerro Negro', 'SC');
INSERT INTO city (id, name, state) VALUES (4377, 'Chapadão do Lageado', 'SC');
INSERT INTO city (id, name, state) VALUES (4378, 'Chapecó', 'SC');
INSERT INTO city (id, name, state) VALUES (4379, 'Cocal do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4380, 'Concórdia', 'SC');
INSERT INTO city (id, name, state) VALUES (4381, 'Cordilheira Alta', 'SC');
INSERT INTO city (id, name, state) VALUES (4382, 'Coronel Freitas', 'SC');
INSERT INTO city (id, name, state) VALUES (4383, 'Coronel Martins', 'SC');
INSERT INTO city (id, name, state) VALUES (4384, 'Corupá', 'SC');
INSERT INTO city (id, name, state) VALUES (4385, 'Correia Pinto', 'SC');
INSERT INTO city (id, name, state) VALUES (4386, 'Criciúma', 'SC');
INSERT INTO city (id, name, state) VALUES (4387, 'Cunha Porã', 'SC');
INSERT INTO city (id, name, state) VALUES (4388, 'Cunhataí', 'SC');
INSERT INTO city (id, name, state) VALUES (4389, 'Curitibanos', 'SC');
INSERT INTO city (id, name, state) VALUES (4390, 'Descanso', 'SC');
INSERT INTO city (id, name, state) VALUES (4391, 'Dionísio Cerqueira', 'SC');
INSERT INTO city (id, name, state) VALUES (4392, 'Dona Emma', 'SC');
INSERT INTO city (id, name, state) VALUES (4393, 'Doutor Pedrinho', 'SC');
INSERT INTO city (id, name, state) VALUES (4394, 'Entre Rios', 'SC');
INSERT INTO city (id, name, state) VALUES (4395, 'Ermo', 'SC');
INSERT INTO city (id, name, state) VALUES (4396, 'Erval Velho', 'SC');
INSERT INTO city (id, name, state) VALUES (4397, 'Faxinal dos Guedes', 'SC');
INSERT INTO city (id, name, state) VALUES (4398, 'Flor do Sertão', 'SC');
INSERT INTO city (id, name, state) VALUES (4399, 'Florianópolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4400, 'Formosa do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4401, 'Forquilhinha', 'SC');
INSERT INTO city (id, name, state) VALUES (4402, 'Fraiburgo', 'SC');
INSERT INTO city (id, name, state) VALUES (4403, 'Frei Rogério', 'SC');
INSERT INTO city (id, name, state) VALUES (4404, 'Galvão', 'SC');
INSERT INTO city (id, name, state) VALUES (4405, 'Garopaba', 'SC');
INSERT INTO city (id, name, state) VALUES (4406, 'Garuva', 'SC');
INSERT INTO city (id, name, state) VALUES (4407, 'Gaspar', 'SC');
INSERT INTO city (id, name, state) VALUES (4408, 'Governador Celso Ramos', 'SC');
INSERT INTO city (id, name, state) VALUES (4409, 'Grão Pará', 'SC');
INSERT INTO city (id, name, state) VALUES (4410, 'Gravatal', 'SC');
INSERT INTO city (id, name, state) VALUES (4411, 'Guabiruba', 'SC');
INSERT INTO city (id, name, state) VALUES (4412, 'Guaraciaba', 'SC');
INSERT INTO city (id, name, state) VALUES (4413, 'Guaramirim', 'SC');
INSERT INTO city (id, name, state) VALUES (4414, 'Guarujá do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4415, 'Guatambú', 'SC');
INSERT INTO city (id, name, state) VALUES (4416, 'Herval D''Oeste', 'SC');
INSERT INTO city (id, name, state) VALUES (4417, 'Ibiam', 'SC');
INSERT INTO city (id, name, state) VALUES (4418, 'Ibicaré', 'SC');
INSERT INTO city (id, name, state) VALUES (4419, 'Ibirama', 'SC');
INSERT INTO city (id, name, state) VALUES (4420, 'Içara', 'SC');
INSERT INTO city (id, name, state) VALUES (4421, 'Ilhota', 'SC');
INSERT INTO city (id, name, state) VALUES (4422, 'Imaruí', 'SC');
INSERT INTO city (id, name, state) VALUES (4423, 'Imbituba', 'SC');
INSERT INTO city (id, name, state) VALUES (4424, 'Imbuia', 'SC');
INSERT INTO city (id, name, state) VALUES (4425, 'Indaial', 'SC');
INSERT INTO city (id, name, state) VALUES (4426, 'Iomerê', 'SC');
INSERT INTO city (id, name, state) VALUES (4427, 'Ipira', 'SC');
INSERT INTO city (id, name, state) VALUES (4428, 'Iporã do Oeste', 'SC');
INSERT INTO city (id, name, state) VALUES (4429, 'Ipuaçu', 'SC');
INSERT INTO city (id, name, state) VALUES (4430, 'Ipumirim', 'SC');
INSERT INTO city (id, name, state) VALUES (4431, 'Iraceminha', 'SC');
INSERT INTO city (id, name, state) VALUES (4432, 'Irani', 'SC');
INSERT INTO city (id, name, state) VALUES (4433, 'Irati', 'SC');
INSERT INTO city (id, name, state) VALUES (4434, 'Irineópolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4435, 'Itá', 'SC');
INSERT INTO city (id, name, state) VALUES (4436, 'Itaiópolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4437, 'Itajaí', 'SC');
INSERT INTO city (id, name, state) VALUES (4438, 'Itapema', 'SC');
INSERT INTO city (id, name, state) VALUES (4439, 'Itapiranga', 'SC');
INSERT INTO city (id, name, state) VALUES (4440, 'Itapoá', 'SC');
INSERT INTO city (id, name, state) VALUES (4441, 'Ituporanga', 'SC');
INSERT INTO city (id, name, state) VALUES (4442, 'Jaborá', 'SC');
INSERT INTO city (id, name, state) VALUES (4443, 'Jacinto Machado', 'SC');
INSERT INTO city (id, name, state) VALUES (4444, 'Jaguaruna', 'SC');
INSERT INTO city (id, name, state) VALUES (4445, 'Jaraguá do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4446, 'Jardinópolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4447, 'Joaçaba', 'SC');
INSERT INTO city (id, name, state) VALUES (4448, 'Joinville', 'SC');
INSERT INTO city (id, name, state) VALUES (4449, 'José Boiteux', 'SC');
INSERT INTO city (id, name, state) VALUES (4450, 'Jupiá', 'SC');
INSERT INTO city (id, name, state) VALUES (4451, 'Lacerdópolis', 'SC');
INSERT INTO city (id, name, state) VALUES (4452, 'Lages', 'SC');
INSERT INTO city (id, name, state) VALUES (4453, 'Laguna', 'SC');
INSERT INTO city (id, name, state) VALUES (4454, 'Lajeado Grande', 'SC');
INSERT INTO city (id, name, state) VALUES (4455, 'Laurentino', 'SC');
INSERT INTO city (id, name, state) VALUES (4456, 'Lauro Muller', 'SC');
INSERT INTO city (id, name, state) VALUES (4457, 'Lebon Régis', 'SC');
INSERT INTO city (id, name, state) VALUES (4458, 'Leoberto Leal', 'SC');
INSERT INTO city (id, name, state) VALUES (4459, 'Lindóia do Sul', 'SC');
INSERT INTO city (id, name, state) VALUES (4460, 'Lontras', 'SC');
INSERT INTO city (id, name, state) VALUES (4461, 'Luiz Alves', 'SC');
INSERT INTO city (id, name, state) VALUES (4462, 'Luzerna', 'SC');
INSERT INTO city (id, name, state) VALUES (4463, 'Macieira', 'SC');
INSERT INTO city (id, name, state) VALUES (4464, 'Mafra', 'SC');
INSERT INTO city (id, name, state) VALUES (4465, 'Major Gercino', 'SC');
INSERT INTO city (id, name, state) VALUES (4466, 'Major Vieira', 'SC');
INSERT INTO city (id, name, state) VALUES (4467, 'Maracajá', 'SC');
INSERT INTO city (id, name, state) VALUES (4468, 'Maravilha', 'SC');
INSERT INTO city (id, name, state) VALUES (4469, 'Marema', 'SC');
INSERT INTO city (id, name, state) VALUES (4470, 'Massaranduba', 'SC');
INSERT INTO city (id, name, state) VALUES (4471, 'Matos Costa', 'SC');
INSERT INTO city (id, name, state) VALUES (4472, 'Meleiro', 'SC');
INSERT INTO city (id, name, state) VALUES (4473, 'Mirim Doce', 'SC');
INSERT INTO city (id, name, state) VALUES (4474, 'Modelo', 'SC');
INSERT INTO city (id, name, state) VALUES (4475, 'Mondaí', 'SC');
INSERT INTO city (id, name, state) VALUES (4476, 'Monte Carlo', 'SC');
INSERT INTO city (id, name, state) VALUES (4477, 'Monte Castelo', 'SC');
INSERT INTO city (id, name, state) VALUES (4478, 'Morro da Fumaça', 'SC');
INSERT INTO city (id, name, state) VALUES (4479, 'Morro Grande', 'SC');
INSERT INTO city (id, name, state) VALUES (4480, 'Navegantes', 'SC');
INSERT INTO city (id, name, state) VALUES (4481, 'Nova Erechim', 'SC');
INSERT INTO city (id, name, state) VALUES (4482, 'Nova Itaberaba', 'SC');
INSERT INTO city (id, name, state) VALUES (4483, 'Nova Trento', 'SC');
INSERT INTO city (id, name, state) VALUES (4484, 'Nova Veneza', 'SC');
INSERT INTO city (id, name, state) VALUES (4485, 'Novo Horizonte', 'SC');
INSERT INTO city (id, name, state) VALUES (4486, 'Orleans', 'SC');
INSERT INTO city (id, name, state) VALUES (4487, 'Otacílio Costa', 'SC');
INSERT INTO city (id, name, state) VALUES (4488, 'Ouro', 'SC');
INSERT INTO city (id, name, state) VALUES (4489, 'Ouro Verde', 'SC');
INSERT INTO city (id, name, state) VALUES (4490, 'Paial', 'SC');
INSERT INTO city (id, name, state) VALUES (4491, 'Painel', 'SC');
INSERT INTO city (id, name, state) VALUES (4492, 'Palhoça', 'SC');
INSERT INTO city (id, name, state) VALUES (4493, 'Palma Sola', 'SC');
INSERT INTO city (id, name, state) VALUES (4494, 'Palmeira', 'SC');
INSERT INTO city (id, name, state) VALUES (4495, 'Palmitos', 'SC');
INSERT INTO city (id, name, state) VALUES (4496, 'Papanduva', 'SC');
INSERT INTO city (id, name, state) VALUES (4497, 'Paraíso', 'SC');
INSERT INTO city (id, name, state) VALUES (4498, 'Passo de Torres', 'SC');
INSERT INTO city (id, name, state) VALUES (4499, 'Passos Maia', 'SC');
INSERT INTO city (id, name, state) VALUES (4500, 'Paulo Lopes', 'SC');
INSERT INTO city (id, name, state) VALUES (4501, 'Pedras Grandes', 'SC');
INSERT INTO city (id, name, state) VALUES (4502, 'Penha', 'SC');
INSERT INTO city (id, name, state) VALUES (4503, 'Peritiba', 'SC');
INSERT INTO city (id, name, state) VALUES (4504, 'Pescaria Brava', 'SC');
INSERT INTO city (id, name, state) VALUES (4505, 'Petrolândia', 'SC');
INSERT INTO city (id, name, state) VALUES (4506, 'Balneário Piçarras', 'SC');
INSERT INTO city (id, name, state) VALUES (4507, 'Pinhalzinho', 'SC');
INSERT INTO city (id, name, state) VALUES (4508, 'Pinheiro Preto', 'SC');
INSERT INTO city (id, name, state) VALUES (4509, 'Piratuba', 'SC');
INSERT INTO city (id, name, state) VALUES (4510, 'Planalto Alegre', 'SC');
INSERT INTO city (id, name, state) VALUES (4511, 'Pomerode', 'SC');
INSERT INTO city (id, name, state) VALUES (4512, 'Ponte Alta', 'SC');

